In [1]:
# Creamos un array en Python

In [2]:
[[123,12,123,12,123],[],[]]

[[123, 12, 123, 12, 123], [], []]

In [3]:
# Ahora creamos un objeto con NUMPY, que aunque tiene apareciencia de un array, no lo es, ya que su tipo es un objeto de numpy
#   como podemos ver en su tipo.

In [4]:
import numpy
n = numpy.arange(27)
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [5]:
type(n)

numpy.ndarray

In [6]:
print(n)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]


In [7]:
n.reshape(3,9)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [8]:
n.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [9]:
print (type (n))
print (n)

<class 'numpy.ndarray'>
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]


In [10]:
# OPEN CV - Importamos el paquete y cargamos una imagen desde el directorio ./resources
#     con el parámetro 0 indicamos que la imagen está en greysacle
#     con el parámetro 1 indicaríamos que está en BGR -> OJO NO ES RGB
# En la variable guardamos los datos numñericos que representan la imagen

In [11]:
import cv2

In [ ]:
# Al imprimirlo en escala de grises 0 representa el negro y 255 el blanco, con valores intermedios de gris.

In [19]:
im_g = cv2.imread("./resources/smallgray.png", 0)
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [22]:
# Al imprimirlo en BGR se generan tres array que representan los valores en Blue, Green y Red.

In [23]:
im_g = cv2.imread("./resources/smallgray.png", 1)
im_g

array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]]], dtype=uint8)

In [24]:
cv2.imwrite("./resources/newsmallgray.png",im_g)

True

In [28]:
im_g = cv2.imread("./resources/smallgray.png", 0)
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [ ]:
# Vamos a ver como podemos ver cada uno de los datos del array imagen
# im_g[0:2] muestra las dos primeras filas del array

In [31]:
im_g[0:2]

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147]], dtype=uint8)

In [ ]:
# im_g[0:2, 2:4] tras una "," podemos elegir los elementos que mostramos dentro de cada uno de los arrays.

In [33]:
im_g[0:2, 2:4]

array([[104, 121],
       [255, 255]], dtype=uint8)

In [35]:
# Podemos mostrar el numero de (filas, columnas) del array

In [36]:
im_g.shape

(3, 5)

In [ ]:
# Mostramos el primer elemento de todos los elementos

In [38]:
im_g[:,0:1]

array([[187],
       [198],
       [209]], dtype=uint8)

In [41]:
# Mostramos un unico elemento, en este caso mostramos el elemento 4 del array 2 (el último elemento del último array)

In [42]:
im_g[2,4]

np.uint8(182)

In [ ]:
# Imprimimos los datos a través de una iteracion

In [45]:
for i in im_g:
    print (i)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [47]:
# Podemos iterar en la matriz traspuesta

In [48]:
for j in im_g.T:
    print(j)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [ ]:
# Tambien podemos imprimir cada uno de los elmentos individualemnte

In [50]:
for i in im_g.flat:
    print (i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [ ]:
# STACKING AND SPLITTING ARRAYS WITH NUMPY

In [52]:
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [ ]:
# HSTACK concatena arrays horizontalmente

In [56]:
ims = numpy.hstack((im_g, im_g))
ims

array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147, 198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8)

In [ ]:
# VSTACK concatena arrays verticalmente

In [58]:
ims = numpy.vstack ((im_g, im_g))
ims

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182],
       [187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [59]:
# Para concatenar dos arrays con hstack o vstack deben tener exactamente las mismas dimensiones.

In [64]:
# HSPLIT parte un array en otros más pequeños
#     La división tiene que poder realizarse en arrays iguales, en el ejemplo que vemos abajo no es posible dividir horizontalmente en 3, pero si en
#     5, con lo que resultan las 5 columnas.

In [65]:
lst = numpy.hsplit (ims, 5)
lst

[array([[187],
        [198],
        [209],
        [187],
        [198],
        [209]], dtype=uint8),
 array([[158],
        [125],
        [134],
        [158],
        [125],
        [134]], dtype=uint8),
 array([[104],
        [255],
        [255],
        [104],
        [255],
        [255]], dtype=uint8),
 array([[121],
        [255],
        [ 97],
        [121],
        [255],
        [ 97]], dtype=uint8),
 array([[143],
        [147],
        [182],
        [143],
        [147],
        [182]], dtype=uint8)]

In [ ]:
# El resultado de HSPLIT es una lista Python, no un objeto Numpy

In [66]:
type (lst)

list